version: '3.4'

# Services/Containers to orchestrate in this composition
services:

  # Basic Python Fast CGI Image Container
  py-fapi-31-slim:
    container_name: py-fapi-31-slim
    tty: true
    restart: unless-stopped
    build: 
      context: .
      target: ${PY_FAPI_31_SLIM_DOCKER_BUILD_TARGET}
      dockerfile: ${DOCKER_BUILD_FILE}
      args:
        - APP_VER=${APP_VER}
      labels:
        com.example.name: "Python FAPI Web Server"
        com.example.description: "${PY_FAPI_31_SLIM_DOCKER_BUILD_DESC}"
        com.example.label-with-empty-value: ""
    image: ${PY_FAPI_31_SLIM_DOCKER_IMAGE}:${PY_FAPI_31_SLIM_DOCKER_IMAGE_TAG}
    environment:
        - APP_VER=${APP_VER}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src:/code/src
    networks:
      - web-app-network

# Custom network for composed containers to communicate on
networks:
  web-app-network:
    driver: bridge
